name: equity-price-direction-predictor
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pandas
  - numpy>=1.26,<2.0
  - pyarrow
  - scikit-learn
  - xgboost
  - lightgbm
  - requests
  - zstandard
  - pytorch
  - transformers
  - pip
  - matplotlib
  - seaborn
  - pip:
      - urllib3<2
      - tensorflow==2.17.1
      - yfinance
      - pytrends
      - vaderSentiment
