name: equity-price-direction-predictor
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pandas
  - numpy
  - pyarrow
  - scikit-learn
  - requests
  - zstandard
  - pytorch
  - transformers
  - pip
  - pip:
      - urllib3<2
      - yfinance
      - pytrends
      - vaderSentiment
